### ISSUE TITLE
Yeast viability calculator

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#55]
As yeasts go bad after a period of time, the viability should be calculated to pitch in the correct amount of yeast. See https://www.morebeer.com/content/yeast_viability_calculator as an example of calculating the yeast viability. Input should be initial cell count and production date and the output should contain viability in percent as well as how many cells are still viable.

Probably you will need a utility to parse date from the command line parameter of different date formats (dd.mm.YYYY or mm/dd/YYYY etc.) 

Add also command to run this calculator from CLI

**Comment by 1jz** [comment]
Hi, I decided to implement this calculator and I have it working on [this](https://github.com/1jz/rustybeer/tree/yeast-viability) branch but, I am not sure which expressions I should use for calculating the yeast viability.

https://www.morebeer.com/content/yeast_viability_calculator 
This site uses `97 - (0.7 * x)` where `x` is the # of days since the production date
(This is what I currently use on my branch)

http://www.yeastcalculator.com/yeastcalc.html
This site uses `97 * 2.72^(-0.008 * x)` where `x` is the # of days since the production date

Here's a desmos chart with the two expressions for comparison: https://www.desmos.com/calculator/t6e47onbze

There is a third expression which is a nonlinear regression on the values I got from https://www.morebeer.com/content/yeast_viability_calculator which is very similar to the `97 * 2.72^(-0.008 * x)` expression

Let me know which expression you'd like me to implement and I'll make a pull request

**Comment by drodil** [comment]
Hi!
I think 97 * 2.72^(-0.008 * x) is the best option so let's go with that. Thanks for your contribution!
